name: pdm5
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython # a powerful Python shell
  - jupyter # to edit and run Jupyter notebooks
  - jupyter_client
  - matplotlib # beautiful plots. See tutorial tools_matplotlib.ipynb
  - numpy # Powerful n-dimensional arrays and numerical computing tools
  - python # Python! Not using latest version as some libs lack support
  - scipy # scientific/technical computing library
  - ipympl
  - cvxpy
  - ffmpeg
  - tqdm # progress bars
  - pyomo
  - glpk
  - scikit-learn